# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Travels Near and Far
tagline:             'Not where, but with Who'
description:         ' Look close by for the things to sustain you. '
url:                 http://ezrider.github.io
baseurl:             ''
#paginate:            5
#gems: [jekyll-paginate]
plugins:
  - jekyll-paginate
paginate: 2

# About/contact
author:
  name:              Mike Beaulieu
  url:               
  email:             michael.e.beaulieu@gmail.com

# Custom vars
version:             1.0.0

collections:
  statusupdates:
    output: true
